# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure AnonymousOverflow path exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ reactflux_uid }}"
    group: "{{ reactflux_gid }}"
  with_items:
    - "{{ reactflux_base_path }}"

- name: Ensure AnonymousOverflow support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ reactflux_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ reactflux_uid }}"
    group: "{{ reactflux_gid }}"
  with_items:
    - env
    - labels

- name: Ensure AnonymousOverflow container image is pulled
  community.docker.docker_image:
    name: "{{ reactflux_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ reactflux_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else reactflux_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure AnonymousOverflow container network is created
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ reactflux_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure AnonymousOverflow systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/reactflux.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ reactflux_identifier }}.service"
    mode: "0644"
