# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform ReactFlux installation tasks
  when: reactflux_enabled | bool
  tags:
    - setup-all
    - setup-reactflux
    - install-all
    - install-reactflux
  block:
    - name: Validate ReactFlux configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install ReactFlux
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform ReactFlux uninstallation tasks
  when: not reactflux_enabled | bool
  tags:
    - setup-all
    - setup-reactflux
  block:
    - name: Uninstall ReactFlux
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
