# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if required ReactFlux settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - reactflux_uid
    - reactflux_gid
    - reactflux_hostname
    - reactflux_path_prefix
    - reactflux_container_network

- name: Run if Traefik is enabled
  when: reactflux_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required ReactFlux Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - reactflux_container_labels_traefik_hostname
        - reactflux_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `reactflux_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if reactflux_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          reactflux_container_labels_traefik_path_prefix (`{{ reactflux_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/reactflux`).
      when: "reactflux_container_labels_traefik_path_prefix != '/' and reactflux_container_labels_traefik_path_prefix[-1] == '/'"
